In [34]:
import numpy as np
import torch
from torch.utils import data as data
from d2l import torch as d2l

# data/model+loss+optimize/train

# 1 dataset

In [5]:
true_w = torch.tensor?

In [29]:
true_w = torch.tensor([2.,3.,4.])
true_b = torch.tensor([5.0])

In [91]:
d2l.synthetic_data?

In [40]:
features,labels = d2l.synthetic_data(true_w,true_b,1000)

In [41]:
features

tensor([[ 1.3361,  0.5717, -0.5601],
        [ 0.3164, -0.3525, -0.0363],
        [-0.9356,  0.0513, -0.6181],
        ...,
        [ 1.1847, -0.3986,  1.1630],
        [ 0.1090,  0.0078, -0.2054],
        [-0.3050,  0.5119, -0.4406]])

In [42]:
labels.shape

torch.Size([1000, 1])

# 2 model/loss/optimize

In [49]:
net = torch.nn.Linear?

In [50]:
net = torch.nn.Linear(in_features=3,out_features=1,bias = True)

## 2.1 init parameter

In [56]:
net.weight.data.normal_(mean=0,std=1)

tensor([[-0.6803,  0.8429,  0.9100]])

In [59]:
net.bias.data.fill_(0)

tensor([0.])

## 2.2 loss

In [74]:
loss_func = torch.nn.MSELoss()

In [75]:
loss_func?

## 2.3 optimize

In [63]:
optimize = torch.optim.SGD?

In [85]:
optimize = torch.optim.SGD(net.parameters(),lr=0.003)

In [86]:
net.parameters()

<generator object Module.parameters at 0x134f46820>

# 3 train

In [87]:
def load_array(dataset,batch_size,is_train=True):
    dataset = data.TensorDataset(*dataset)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [88]:
batch_size = 10
data_iter = load_array((feature,labels),batch_size=batch_size)

In [89]:
num_epochs = 100

In [90]:
for i in range(num_epochs):
    for x,y in data_iter:
        pred_y = net(x)
        loss = loss_func(pred_y,y)
        optimize.zero_grad()
        loss.backward()
        optimize.step()
    if i%5 == 0:
        print('loss',loss_func(net(features),labels))
        print('weight',net.weight.data)
        print('bias',net.bias.data)

loss tensor(28.9891, grad_fn=<MseLossBackward>)
weight tensor([[-0.3655,  0.2544,  0.1559]])
bias tensor([5.1896])
loss tensor(29.2729, grad_fn=<MseLossBackward>)
weight tensor([[-0.2913,  0.1837,  0.1193]])
bias tensor([5.1427])
loss tensor(29.5880, grad_fn=<MseLossBackward>)
weight tensor([[-0.2914,  0.2242,  0.0580]])
bias tensor([5.1514])
loss tensor(29.5778, grad_fn=<MseLossBackward>)
weight tensor([[-0.2922,  0.1707,  0.0916]])
bias tensor([5.1485])
loss tensor(29.6200, grad_fn=<MseLossBackward>)
weight tensor([[-0.3126,  0.1715,  0.0984]])
bias tensor([5.1597])
loss tensor(29.4735, grad_fn=<MseLossBackward>)
weight tensor([[-0.3194,  0.2069,  0.0983]])
bias tensor([5.1468])
loss tensor(29.7443, grad_fn=<MseLossBackward>)
weight tensor([[-0.3093,  0.1897,  0.0707]])
bias tensor([5.1545])
loss tensor(29.7643, grad_fn=<MseLossBackward>)
weight tensor([[-0.2976,  0.1644,  0.0767]])
bias tensor([5.1568])
loss tensor(29.4444, grad_fn=<MseLossBackward>)
weight tensor([[-0.2949,  0.2067