In [1]:
import torch

# data/model/loss/optimize/init/train

# data

# model

In [16]:
torch.tensordot?

In [22]:
torch.nn.Softmax?

In [27]:
class MultiHeadAttention(torch.nn.Module):
    def __init__(self,num_head=4,dim_hidden=256,):
        super(MultiHeadAttention,self).__init__()
        ##query,key,value
        self.num_head = num_head
        self.dim_head = dim_hidden/4
        self.proj_q = torch.nn.Linear(in_features=dim_hidden,out_features=num_head*self.dim_head)
        self.proj_k = torch.nn.Linear(in_features=dim_hidden,out_features=num_head*self.dim_head)
        self.proj_v = torch.nn.Linear(in_features=dim_hidden,out_features=num_head*self.dim_head)
        
        self.sfm = torch.nn.Softmax()
    
    def forward(self,query,key,value,mask):
        ##[batch_size,seq_len,dim]
        query = self.proj_q(query)
        key = self.proj_q(query)
        value=selff.proj_q(query)
        
        ##[batch_size,num_head,seq_len,dim_head]
        query = self.split_head(query)
        key = self.split_head(key)
        value = self.split_head(value)
        
        ##attention
        ##[[batch_size,num_head,seq_len,dim_head]]->[batch_size,num_head,seq_len,seq_len]
        att_weight = torch.tensordot(query,key,dims=([-1],[-1]))
        scaled_ratio = torch.sqrt(query.shape[-1])
        att_weight/=scaled_ratio
        ##mask: batch_size,seq_len,seqq_len
        ##causal mask for decoder and padding_mask for encoder and decoder
        if mask is not None:
            att_weight += (1-mask)*-1*e**9
        att_weight = self.sfm(att_weight)
        
        ##[batch_size,num_head,seq_len,seq_len] *[batch_size,num_head,seq_len,dim_head]
        output = torch.tensordot(att_weight,value,dims=([-1],[-1]))
        output = torch.permute(output,[0,2,1,3]).view(output.shape[0],output.shape[1],-1)
        return output
        
        
    def split_head(self,x):
        ##[batch_size,seq_len,dim]->##[batch_size,seq_len,num_head,dim_head]
        x = x.view(x.shape[0] ,x.shape[1],self.num_head,-1)
        #[batch_size,seq_len,num_head,dim_head]->#[batch_size,num_head,seq_len,dim_head]
        x = torch.permute(x,[0,2,1,3])
        return x    def post_init(self):n        for m in self.modules():
            if isinstance(m, torch.nn.Linear):
                # print('before',m.weight,)
                torch.nn.init.xavier_normal(m.weight)
                #print('after',m.weight)
                if m.bias is not None:
                    m.bias.data.zero_()


In [23]:
a = torch.arange(60.).reshape(3, 4, 5)
b = torch.arange(60.).reshape(3, 4, 5)

In [25]:
torch.tensordot(a,b,dims=([-1],[-1])).shape

torch.Size([3, 4, 3, 4])

In [29]:
torch.arange(1,10).repeat(2,1)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
torch.nn.MultiheadAttention??

In [33]:
torch.nn.functional.multi_head_attention_forward??

In [43]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
d2l.MultiHeadAttention??

In [45]:
torch.repeat_interleave?

In [47]:
d2l.sequence_mask??

In [50]:
torch.arange((10)) < torch.arange(1,11)

tensor([True, True, True, True, True, True, True, True, True, True])